image: debian/stable
packages:
  - wget
sources:
  - https://git.sr.ht/~retzoh/taskbot
environment:
  REPOSITORY_NAME: taskbot
  PACKAGE_NAME: taskbot
  PACKAGE_FOLDER: taskbot
  PACKAGE_PATH: .
  GIT_SR_HT_URL: git@git.sr.ht:~retzoh/taskbot
  GITHUB_URL: git@github.com:Retzoh/taskbot.git
secrets:
  - ed37ce69-d5be-42df-9b92-41471089d431  # ~/.ssh/known_hosts
  - 899472e5-1ec8-4211-a00b-05a0d3eaf775  # ~/.ssh/.github_deploy_ssh_key
  - 7a15e00a-ada6-463e-a145-31c3297d95ec  # ~/.cloudflare/api_keys
tasks:
- setup_nvm: |
    wget -nv -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.buildenv
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> .buildenv

- setup_npm: |
    nvm --version
    nvm install node

    npm install -g npx

- install_dependencies: |
    npm --version
    cd $REPOSITORY_NAME

    npm install

    npx elm --version

    npx wrangler --version

- test: |
    cd $REPOSITORY_NAME

    npm run test_coverage

- build: |
    cd $REPOSITORY_NAME

    # npm run build
    npm run make
    npm run minify
    npm run escape_code
    npm run build_worker

- integration_tests: |
    echo "TODO"

- deploy_master: |
    ln -sf ~/.ssh/.build_test_ssh_key ~/.ssh/id_rsa

    cd $REPOSITORY_NAME
    git remote set-url origin $GIT_SR_HT_URL
    lines=`git diff --stat origin/master..HEAD | wc -l`
    if [ $lines -eq 0 ]
    then

    # deploy code
    git config --global user.email "~retzoh/builds@lists.sr.ht"
    git config --global user.name "Deploy"

    ln -sf ~/.ssh/.github_deploy_ssh_key ~/.ssh/id_rsa
    git checkout -B master -t origin/master
    git remote set-url origin $GITHUB_URL
    git push --set-upstream origin master

    # deploy worker
    set +x
    . ~/.cloudflare/api_keys
    set -x
    npm run publish

    else

    echo "Aborting github deployment: HEAD is dirty compared to master."

    fi
